#!/usr/bin/env bash
set -e

# Based on https://gohugo.io/hosting-and-deployment/hosting-on-github/#put-it-into-a-script-1

BRANCH=web
DIR=$(dirname "$0")
cd $DIR/..

if [[ $(git status -s) ]]
then
    echo "The working directory is dirty. Please commit any pending changes."
    exit 1;
fi

echo "Deleting old publication"
rm -rf public
mkdir public
git worktree prune

echo "Checking out '$BRANCH' branch into public"
git worktree add -B web public origin/$BRANCH

echo "Removing existing files"
rm -rf public/*

echo "Generating site"
hugo

echo "Updating '$BRANCH' branch"
cd public
git add --all
git commit -m "Publish via script"
git push
